### ISSUE TITLE
Record Meeting

### ISSUE THREAD

**Issue by chrishurlburt** [zoom/videosdk-ui-toolkit-web#10]
Hi,

Thank you for your work on the UI Toolkit. We're using it in our project and it's working great for our use-case!

We'd like to add the ability to record meetings, ideally without a user needing to click a button in the UI. We'd like all of our meetings to be recorded by default.

Is that possible with this package currently?

**Comment by tommygaessler** [comment]
Hey @chrishurlburt , glad to hear you are liking the UI Toolkit!

Recording automatically is possible today, you could listen for the [Session Started Webhook](https://developers.zoom.us/docs/video-sdk/webhooks/#operation/session.started), and then call the [Start Cloud Recording API](https://developers.zoom.us/docs/video-sdk/apis/#operation/inSessionEventsControl).

There is a related thread here: https://github.com/zoom/videosdk-ui-toolkit-web/issues/6
