### ISSUE TITLE
Virutal background is not supported on your device or browser.

### ISSUE THREAD

**Issue by MEGApixel23** [zoom/videosdk-ui-toolkit-web#11]
I'm using M1 macbook pro and it seems to be working fine on the desktop zoom.

Does UI toolkit support Virutal background as of now?

**Comment by Ticorrian-Heard** [comment]
Hi, Virtual background is supported. While in the meeting, click the settings button and navigate to the backgrounds tab. From there, you can pick your background. Also wanting to confirm I am testing on an M2 Macbook.
<img width="1864" alt="image" src="https://github.com/zoom/videosdk-ui-toolkit-web/assets/72872551/e672c154-9a41-46b5-a885-c3051a62468a">

**Comment by MEGApixel23** [comment]
I have MacBook pro on M1 chip and testing with Crome Version 121.0.6167.160 (Official Build) (arm64).
Here's what I see when trying to enable virtual background (see screenshot):
<img width="1373" alt="Screenshot 2024-02-15 at 12 05 23" src="https://github.com/zoom/videosdk-ui-toolkit-web/assets/4102786/bef1c7cb-3cd7-4d88-bab1-379a3b7f5dda">

**Comment by Ticorrian-Heard** [comment]
Can you make sure you have sharedarraybuffer enabled on your browser: https://developers.zoom.us/docs/meeting-sdk/web/sharedarraybuffer/

**Comment by MEGApixel23** [comment]
@Ticorrian-Heard That solved the problem. With enabling SharedArrayBuffer the Background feature now works. Many thanks!

**Comment by tommygaessler** [comment]
Good suggestion @MEGApixel23 . We will add more details to the documentation/README.
