### ISSUE TITLE
Hide exit/leave button

### ISSUE THREAD

**Issue by AlexanderKapelyukhovskiy** [zoom/videosdk-ui-toolkit-web#12]
Thank you for providing UI Toolkit. It is really simplifying  integration of zoom video chat into websites.

In my use case I need to have a control of ending session outside of Video component.
Is there a simple way to hide exit/leave button on panel with buttons ?

**Comment by AlexanderKapelyukhovskiy** [comment]
I managed to hide button with help of css

**Comment by tommygaessler** [comment]
Hey @AlexanderKapelyukhovskiy , yes, you may hide the buttons via CSS or JS.

We are working on opening up more flexibility of the control bar and each component. 

To end the session outside of the video component, the host could end the session by clicking the end session button in the UI, or you could use the REST API to do this programmatically on the server side: https://developers.zoom.us/docs/video-sdk/apis/#operation/inSessionEventsControl
