### ISSUE TITLE
Can't get access to ZoomVideoClient  inside UI toolkit

### ISSUE THREAD

**Issue by AlexanderKapelyukhovskiy** [zoom/videosdk-ui-toolkit-web#13]
I would like to get access to ZoomVideoClient  like this:
```
import { uitoolkit } from '@zoom/videosdk-ui-toolkit';

// Assuming uitoolkit provides an event or callback when a session is joined
uitoolkit.onSessionJoined((sessionInfo: any) => {
    // Access the ZoomVideoClient instance from the sessionInfo object
    const zoomVideoClient = sessionInfo.videoClient;
    // Now you can use zoomVideoClient to access methods or properties of ZoomVideoClient
    zoomVideoClient.getAllUsers().then(users => {
        console.log(users);
    }).catch(error => {
        console.error(error);
    });
});

// Call joinSession method provided by the UI toolkit
uitoolkit.joinSession(/* Pass necessary parameters */);
```
this is no videoClient property in  sessionInfo.  Could you please advise proper way?

**Comment by Ticorrian-Heard** [comment]
Hi! 

This feature is not available as of now for the uikit callback functions. But technically this videoclient object is a singleton so you should be able to import it directly from the base web video sdk by using:
import ZoomVideo, { ErrorTypes as Error } from '@zoom/videosdk';

and retrieve the instance after joining the session using:
 const client = ZoomVideo.createClient();
 console.log(client.getAllUser());

**Comment by AlexanderKapelyukhovskiy** [comment]
For my case I need to have a control over session outside toolkit control. I need to hide leave/exit  button and put same functionality outside. `uitoolkit.closeSession()` is not working well for me.
But in general I would like to have ability to use full SDK functionality. SDK provides so many functions and I don't see a reason of limiting ui toolkit clients to be rooted to only 8 functions from  UIToolkit interface.

**Comment by Ticorrian-Heard** [comment]
I see, thank you for sharing. After discussing with my team, we do not currently have plans of making the videoClient available through a callback. But technically, this videoclient object is a singleton so you should be able to import it directly from the base web video sdk by using:
import ZoomVideo from '@zoom/videosdk';

and retrieve the instance after joining the session using:
const client = ZoomVideo.createClient();
console.log(client.getAllUser());

Please note that this is a workaround and unexpected behavior with the UI updates might occur depending on the features you choose to use. In that case, support from my team is limited.

**Comment by AlexanderKapelyukhovskiy** [comment]
Thank you for your support! I appreciate prompt response!

**Comment by jabza** [comment]
this work around doesn't appear to work anymore :(

**Comment by tommygaessler** [comment]
Hey @AlexanderKapelyukhovskiy , @jabza , we have released 2.1.0-1 and this was added. Please read through the other updates as well:

https://developers.zoom.us/changelog/ui-toolkit/web/2.1.0-1/
https://developers.zoom.us/docs/video-sdk/web/ui-toolkit/

**Comment by bUxEE** [comment]
Even using latest verion of toolkit is seems the singleton approach does not work
I have tried the `createClient `approach but it doesn't seem to return the same instance. binding listeners does not work, and logging `getAllUser` always returns empty array even if multiple users connected


```
  import { ref } from 'vue'

  import ZoomVideo from "@zoom/videosdk";
  import uitoolkit from "@zoom/videosdk-ui-toolkit";
  import '@zoom/videosdk-ui-toolkit/dist/videosdk-ui-toolkit.css'

  var config = {
      videoSDKJWT: 'XXXXXX',
      sessionName: 'test',
      userName: 'host',
      features: ['preview', 'video', 'audio', 'settings', 'share', 'recording', 'share'],
      options: { 
        init: {
          enforceVirtualBackground: true,
          leaveOnPageUnload: true,
          patchJsMedia: true,
          stayAwake: true
        }, 
        audio: {
          autoStartAudioInSafari: true,
          mute: false
        }, 
        video: {}, 
        share: {}
      },
      virtualBackground: {
         allowVirtualBackground: true,
         allowVirtualBackgroundUpload: true,
         virtualBackgrounds: ['https://images.unsplash.com/photo-1715490187538-30a365fa05bd?q=80&w=1945&auto=format&fit=crop']
      }
  };

  const uitoolkitContainer = ref(null)
  const controlsContainer = ref(null)
  const videoContainer = ref(null)

  const init = () => {
    document.getElementById('join-flow').style.display = 'none'

    joinSession()

    const zoomClient = ZoomVideo.createClient();

    console.log("zoomClient",zoomClient)
    console.log("getAllUser",zoomClient.getAllUser()); //always return empty array

    zoomClient.on('active-speaker', (payload) => {
      console.log('Active speaker, use for CSS visuals', payload) // never logs
    })

    zoomClient.on('video-active-change', (payload) => {
      console.log('video-active-change', payload) // never logs
    })

    uitoolkit.onSessionClosed(sessionClosed)
  }

  const joinSession = () => {
    uitoolkit.showUitoolkitComponents(uitoolkitContainer.value, config)

    uitoolkit.showControlsComponent(controlsContainer.value)

    uitoolkit.showVideoComponent(videoContainer.value)
  }

  const sessionClosed = (() => {
    console.log('session closed')
    uitoolkit.closeSession(uitoolkitContainer.value)

    document.getElementById('join-flow').style.display = 'block'
  })
```

**Comment by Ticorrian-Heard** [comment]
Hi @bUxEE,

It looks like you might be running into a race condition since the joining operation is async and you're not awaiting the completion of that flow. Can you try to putting the createClient() function inside of a callback function and pass that callback into the onUserAdded listener? Something like:

```
client.on('user-added',(payload)=>{
 const zoomClient = ZoomVideo.createClient();
})
```

or within the .join() function when you enter the session:

```
client.join(topic, token, userName, password).then(() => {
  stream = client.getMediaStream()
  const zoomClient = ZoomVideo.createClient();
}).catch((error) => {
  console.log(error)
})
```

**Comment by bUxEE** [comment]
Sorry but I do not seem to understand, where is the `client` you refer to instantiated?
All I have beofre calling `Zoomvideo.createClient()` is the `uitoolkit ` instance

**Comment by klocus** [comment]
@tommygaessler Also looking forward to fixing this! :-)

**Comment by loop-dev-github** [comment]
For anyone that is facing this issue, I have found a workaround but it is a bit weird..
I went into `node_modules/@zoom/videosdk-ui-toolkit/dist/videosdk-ui-toolkit.js` file and looked for `this.videoSdkService`, in there I did a concurrent edit, I selected everything that has `this.videoSdkService=` went before the comma and added `window.sdkService=this.videoSdkService,` dont forget to add another comma, after that don't forget to commit the patch with `bun patch commit` or `patch-package` library and after it you can access the client by going to `window.sdkService.client` I take into an internal variable after the `onSessionJoined` event.

Hope this helps until we have a better solution 🙏

**Comment by rajihawa** [comment]
For anyone that is facing this issue, I have found a workaround but it is a bit weird..
I went into `node_modules/@zoom/videosdk-ui-toolkit/dist/videosdk-ui-toolkit.js` file and looked for `this.videoSdkService`, in there I did a concurrent edit, I selected everything that has `this.videoSdkService=` went before the comma and added `window.sdkService=this.videoSdkService,` dont forget to add another comma, after that don't forget to commit the patch with `bun patch commit` or `patch-package` library and after it you can access the client by going to `window.sdkService.client` I take into an internal variable after the `onSessionJoined` event.

Hope this helps until we have a better solution 🙏

**Comment by klocus** [comment]
> Hey [@bUxEE](https://github.com/bUxEE) , we will be enhancing this in the next release.

@tommygaessler Has this been addressed in the latest release?
