### ISSUE TITLE
Integrating Preview Control with Video Control in Zoom UI Toolkit

### ISSUE THREAD

**Issue by AlexanderKapelyukhovskiy** [zoom/videosdk-ui-toolkit-web#16]
Description:
I'm working on implementing a video chat feature where users can preview their camera and microphone settings before starting a video session. Once the user is comfortable with their settings, they can initiate the video session. For this purpose, I plan to use the Preview control on the waiting screen and the Video control from the Zoom UI Toolkit on the video session screen.

Question:
Is there a way to seamlessly pass the selected camera and microphone settings from the Preview control to the Video control? This would ensure a smooth transition for users and maintain consistency in their chosen settings throughout the video session experience.

Objective:
To provide users with a convenient and intuitive way to preview and manage their camera and microphone settings before and during a video session, enhancing the overall usability and user experience of the application.

**Comment by AlexanderKapelyukhovskiy** [comment]
Thank you for your response! I'm genuinely pleased to hear about this exciting news. Could you kindly provide any details regarding when we can expect to see this feature? Your insight would be greatly appreciated.

**Comment by tommygaessler** [comment]
Hey @AlexanderKapelyukhovskiy , @itsmepetrov , we are code complete with this feature and finishing up testing, then we will release.

**Comment by misterdebug** [comment]
Hi, I need this feature too :)

**Comment by tommygaessler** [comment]
Thank you @misterdebug , preview control is our upcoming release this month! Stay tuned!

**Comment by tommygaessler** [comment]
Hey @AlexanderKapelyukhovskiy , @itsmepetrov , @misterdebug , @shishirsharma ,

I am happy to share we have improved the preview flow with the UI Toolkit. If you include `preview` in the features array, it will show the enhanced preview page, let the user configure their devices and background, and join with video / microphone on or off. 

Changelog: https://developers.zoom.us/changelog/ui-toolkit/web/1.12.1-1
Docs: https://developers.zoom.us/docs/video-sdk/web/ui-toolkit/#create-a-configuration-object

**Comment by misterdebug** [comment]
Thanks @tommygaessler, i will test it :)
