### ISSUE TITLE
Overwrite end call button

### ISSUE THREAD

**Issue by alexnechifor** [zoom/videosdk-ui-toolkit-web#17]
Hello! I'm using this toolkit since I only need 1 on 1 calls. Is there any way to overwrite the end call button? I just want to end the session and not display the option to either leave or end. 
Not only by host, but by other participant too. When one of them presses the button, just end the session.

Thanks!

**Comment by tommygaessler** [comment]
Hey @alexnechifor , good suggestion, we will evaluate this, but currently only the host or the REST API can end the session. However, if all users leave the session, the session will also end.

In the meantime, you could use a custom button with the REST API to end the session:

https://developers.zoom.us/docs/video-sdk/apis/#operation/sessionStatus

**Comment by alexnechifor** [comment]
Hey @tommygaessler ! Thanks for your answer, I really appreciate it. I'm really looking forward to use this toolkit in my app, I'm just wondering, do you plan to release any updates to it, to make it more customizable let's say?

**Comment by tommygaessler** [comment]
Hey @alexnechifor , I am happy to hear you are looking forward to using the UI Toolkit! 

We are planning some exciting updates to it, and to customize some aspects. What type of customization are you looking for?

In terms of getting the Session ID, you can easily get the Session ID from the user interface, in the settings panel, or by calling the Get Sessions API, setting a query param of your session name:

GET `https://api.zoom.us/v2/videosdk/sessions?session_name=my session`

https://developers.zoom.us/docs/video-sdk/apis/#operation/sessions

**Comment by alexnechifor** [comment]
Thank you! Excited to hear that you are planning updates!

Well, I have some suggestions for customization:
- Be able to skip the "enable audio" dialog and just enable it by calling a function
- Same for microphone, camera, maybe add an option to have them enabled by default
- As I mentioned earlier, to be able to overwrite/customize my end call button
- Maybe add some custom hooks, for example one to get some data about the session

Good luck! I'm looking forward to it!

**Comment by tommygaessler** [comment]
Good suggestions @alexnechifor , we will evaluate these!

**Comment by tommygaessler** [comment]
Hey @alexnechifor , we have improved the preview flow, which allows the user to join with audio enabled, which elevates the need for the enable audio dialog.

Give it a try: https://developers.zoom.us/changelog/ui-toolkit/web/1.12.1-1
Docs: https://developers.zoom.us/docs/video-sdk/web/ui-toolkit/
