### ISSUE TITLE
Components related methods missing from 1.10.8-2 npm package

### ISSUE THREAD

**Issue by quentinhayot** [zoom/videosdk-ui-toolkit-web#27]
Hi,

According to the release notes and documentation, the 1.10.8-2 package should offer the following methods:
```javascript
uitoolkit.showUitoolkitComponents()
uitoolkit.hideUiToolkitComponents()
// and all other components related methods
```

But it seems that they are missing. My IDE complains about them and my Angular project won't build with 
```
Application bundle generation failed. [1.160 seconds]

✘ [ERROR] TS2339: Property 'showUitoolkitComponents' does not exist on type 'typeof _default'. [plugin angular-compiler]

    src/app/conf-visio/conf-visio.component.ts:92:26:
      92 │ ...          uitoolkit.showUitoolkitComponents(sessionContainer!, ...
         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by RexzZzY** [comment]
`declare namespace _default {
    function openPreview(container: HTMLElement): void;
    function closePreview(container: HTMLElement): void;
    function joinSession(container: HTMLElement, config: Object): void;
    function closeSession(container: HTMLElement): void;
    function onSessionJoined(callback: EventListenerOrEventListenerObject): void;
    function offSessionJoined(callback: EventListenerOrEventListenerObject): void;
    function onSessionClosed(callback: EventListenerOrEventListenerObject): void;
    function offSessionClosed(callback: EventListenerOrEventListenerObject): void;
}
export default _default;`

seems those functions are not exported / packed

**Comment by quentinhayot** [comment]
That was an easy fix, the prototypes where just missing from the index.d.ts as @RexzZzY noted.

**Comment by tommygaessler** [comment]
Hey @quentinhayot , @RexzZzY , we will fix in the next release, thank you for sharing.

**Comment by tommygaessler** [comment]
Hey @quentinhayot , @RexzZzY , this is fixed now in the latest release:

https://developers.zoom.us/changelog/ui-toolkit/web/1.12.1-1
