### ISSUE TITLE
Audio and Video Persistence After Session End and Even When Not in Use

### ISSUE THREAD

**Issue by bharat-mobiuso** [zoom/videosdk-ui-toolkit-web#29]
I'm experiencing unexpected audio and video accessibility issues while using the Zoom Video SDK UI Toolkit for the web. Even when audio and video are not in use or after a session ends, they seem to remain accessible. 

I'm currently working with versions 1.12.1-1 of the UI Toolkit and 1.12.1 of the Video SDK.

**Comment by bharat-mobiuso** [comment]
#### Issue Closed: Resolved through code refactoring

After careful review and refactoring of the code, I have identified and corrected the issue that was causing audio and video to remain accessible even when they were not in use or after a session ended.

**Comment by tommygaessler** [comment]
Hey @bharat-mobiuso , was this issue in the UI Toolkit itself or you not handling the clean up flow? 

https://developers.zoom.us/docs/video-sdk/web/ui-toolkit/#clean-up-the-session

Glad to hear you have it resolved, but please let us know if you have any feedback.
