### ISSUE TITLE
When video is start then sometimes got below error in.

### ISSUE THREAD

**Issue by govindp-reconnectin** [zoom/videosdk-ui-toolkit-web#32]
see below error
![uikitissue](https://github.com/user-attachments/assets/f96b3c82-4620-4145-8e06-3061bc26839c)

My implementation code are below

var config = {
	   videoSDKJWT: $('#zoom_video_token').val(),
	   sessionName: $('#sessionName').val(),
	   userName: $('#userIdentity').val(),
	   features: ['video', 'audio', 'chat', 'users', 'settings'],
         options: { init: {enforceVirtualBackground:true}, audio: {originalSound:false}, video: {virtualBackground:false,originalRatio:true}, share: {}},
      virtualBackground: {
    allowVirtualBackground: true,
    allowVirtualBackgroundUpload: true,
    virtualBackgrounds: [$('#weburl').val()+'/zoombg.jpg']
  }

	}

	var sessionContainer = document.getElementById('sessionContainer')

	uitoolkit.joinSession(sessionContainer, config)
    	var sessionClosed = (() => {
    	
})

      uitoolkit.onSessionClosed(sessionClosed);

**Comment by tommygaessler** [comment]
Hey @govindp-reconnectin , 

Can you please share an example config with the values, including JWT so I can help debug.

Best,
Tommy

**Comment by govindp-reconnectin** [comment]
Hey @tommygaessler 

Thank you for your reply. The issue is resolved.

**Comment by tommygaessler** [comment]
Glad to hear!
