### ISSUE TITLE
Setting Mirror my video option configurable

### ISSUE THREAD

**Issue by nabullah** [zoom/videosdk-ui-toolkit-web#37]
Currently, for specific users, I have set a default virtual background image. However, the self-video for these users is mirrored by default, as 'Mirror my video' option is checked by default which also mirrors the virtual background.

Since the background image contains words, mirroring causes the text to appear reversed. Unchecking the "Mirror my video" option fixes this issue, but we want to make this setting default, so users don’t have to do it themselves.

**Comment by AlexanderKapelyukhovskiy** [comment]
I recently observed that the "Mirror my video" checkbox currently affects only the Preview and my own Video box, meaning the mirrored effect is not applied for viewers on the other side of the video call. Consequently, if I select a mirrored background image and enable "Mirror my video," it appears correctly for me, but the background displays in reverse for the other participant.

This behavior seems unintended, as I would expect that when "Mirror my video" is selected, the mirrored effect would be visible to both sides of the video chat.

**Comment by tommygaessler** [comment]
Hey @nabullah , @AlexanderKapelyukhovskiy ,

The mirror my video option is only for your local video. Your video will be received by remote users always in the correct way, as if they were looking at you IRL. 

This logic follows the same logic as our Zoom Meeting Client application. Notice that if I mirror or do not mirror my local video, the user on the right side who is receiving my video stream stays the same. 

![Screenshot 2024-10-31 at 1 16 42 PM](https://github.com/user-attachments/assets/4359a97b-4a61-4fd7-988f-967f4953485c)

![Screenshot 2024-10-31 at 1 16 27 PM](https://github.com/user-attachments/assets/19d28f7f-de2c-4b6a-b18a-d3eb8fee920b)


Best,
Tommy

**Comment by AlexanderKapelyukhovskiy** [comment]
Hi Tommy,

Thank you for the explanation — that clears things up.

Could you confirm the default value for the "Mirror My Video" checkbox? During my testing, it seemed to be set to "true" by default, though I’d like it set to "false."

If my observation is correct, it would be great to allow clients control over this setting so that we could establish the initial value in the Zoom UI Toolkit for Web according to our customers' needs.

Thank you

**Comment by tommygaessler** [comment]
Hey @AlexanderKapelyukhovskiy , that is correct, the default is true. 

We will expose a mirrored option in the config settings in an upcoming release, thank you for the feedback. By the way, would you also want to lock the mirroring option, meaning the user could not change the mirror setting?

**Comment by AlexanderKapelyukhovskiy** [comment]
Hi Tommy!

Thank you for your response!

I think adding configuration for setting the initial value of the "Mirror my video" option, along with the ability to lock it, is a fantastic idea. I really appreciate your proactive approach to enhancing the customer experience.

**Comment by tommygaessler** [comment]
Hey @AlexanderKapelyukhovskiy , we released 2.1.0-1, but I was not able to get this request in this release. We are working to include it in an upcoming release. Stay tuned!

https://developers.zoom.us/changelog/ui-toolkit/web/2.1.0-1/
https://developers.zoom.us/docs/video-sdk/web/ui-toolkit/
